### ISSUE TITLE
Loading in iframe over https does not load content if clicking links

### ISSUE THREAD

**Issue by sklirg** [myth/pepper8#1]
This happens in a TeamCity setup, in the PEP8 report tab.

If I click one of the error codes links in the statistics tab, a blank page gets rendered in the iframe generated by TeamCity. 
![screenshot 2015-10-20 13 27 16](https://cloud.githubusercontent.com/assets/5422571/10605871/11607e14-772f-11e5-9fb5-82ef1403bff5.png)

If I load the unsafe scripts, the page renders.
![screenshot 2015-10-20 13 27 31](https://cloud.githubusercontent.com/assets/5422571/10605872/1160ae02-772f-11e5-8de6-e31a5d46f589.png)

**Comment by myth** [comment]
Fixed in cbe22e0
