### ISSUE TITLE
pepper8 does not output HTML errors with the flake8-commas plugin

### ISSUE THREAD

**Issue by w0rp** [myth/pepper8#3]
I have found a bug in the latest version of `pepper8`
1. Install flake8-commas via `pip install`.
2. Enable the errors by including C812 in a setup.cfg file, or with `--select`.
3. Run `flake8` to get text output.
4. Run `pepper8` on the output of `flake8`.

You will be able to see the standard `flake8` warnings and errors in the HTML output, but not the output resulting from plugins, which are present in the text output.

**Comment by myth** [comment]
Hi, sorry for the long response time. It should work for all error codes now!

**Comment by w0rp** [comment]
Cool, thanks a lot for writing this tool! I personally use it to get a quick overview of any warnings and errors which will be reported in CI, without having to wait for CI.

**Comment by kevinsl** [comment]
Hello, I'm running into a similar issue when using the radon plugin. By adding `--radon-max-cc=1` to my flake8 command I get `R701` errors in the output. For example:

`./settings.py:28:5: R701: 'filter' is too complex (2)`

But they are not included in the pepper8 output.
